# Generated by Django 5.2 on 2025-04-13 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_profile_username_profile_bio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
