# Generated by Django 5.2 on 2025-06-04 18:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_rename_message_message_message_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="content",
            field=ckeditor.fields.RichTextField(default=""),
        ),
    ]
